### ISSUE TITLE
JS array for conf option levelColors doesn't work

### ISSUE THREAD

**Issue by chrim5** [35niavlys/vaadin-justgage#1]
Hi!
First of all, cool plugin! Smooth and simple.
I was playing around with different conf options and got stuck with setting the level colors:
`String[] levelColors = {"#ff0000","#f9c802","#a9d70b"};`
`conf.levelColors = levelColors;`

will result in the following JS code:
`"levelColors":["#ff0000""#f9c802""#a9d70b]`

Should  be:
`"levelColors":["#ff0000","#f9c802","#a9d70b]`

Cheers

**Comment by 35niavlys** [comment]
Hi and thank you for reporting the problem.
I did an update, it should be ok now
