### ISSUE TITLE
Can't refresh gauge with float

### ISSUE THREAD

**Issue by daergoth** [35niavlys/vaadin-justgage#2]
Right now a JustGage instance can only be refreshed with an integer.
However, the core JustGage JavaScript library would support refreshing
with a float value.

This would be a small modification in `JustGage.java` from:
``` java
public void refresh(int value) {
  callFunction("refresh", value);
}
```
to:
``` java
public void refresh(float value) {
  callFunction("refresh", value);
}
```

**Comment by 35niavlys** [comment]
Thanks for the issue. I uploaded the 1.0.2 version
